omap5: sparse fixes for setup_emif_config()
Building for board_uevm with sparse enabled
gives rise to this warning:
arch/omap5/sdram.c:74:6: warning: symbol
'setup_emif_config' was not declared. Should it be static?

This warning can be removed by including file common_proc.h
in arch/omap5/sdram.c. However, this change cause the compiler
to complain with this error:

compile arch/omap5/sdram.c
arch/omap5/sdram.c:74: error: redefinition of 'setup_emif_config'
include/common/common_proc.h:44: note: previous definition of
'setup_emif_config' was here
make: *** [out/omap5uevm/target-obj/arch/omap5/sdram.o] Error 1

This patch fixes these problems and gets rid of the sparse warning.

Change-Id: I76d8f1cc8c6cfacafcaea01140f5ad04776073ca
Signed-off-by: Christina Warren <cawarren@ti.com>